/**
 * Generated by Gas3 v2.0.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR. INSTEAD, EDIT THE INHERITED CLASS (Convidado.as).
 */

package com.apolloti.getmarry.domain {

    import flash.events.EventDispatcher;
    import flash.net.FileReference;
    import flash.utils.IDataInput;
    import flash.utils.IDataOutput;
    import flash.utils.IExternalizable;
    import flash.utils.getQualifiedClassName;
    import mx.core.IUID;
    import mx.utils.UIDUtil;
    import org.granite.collections.IPersistentCollection;
    import org.granite.meta;
    import org.granite.tide.IEntity;
    import org.granite.tide.IEntityManager;
    import org.granite.tide.IPropertyHolder;

    use namespace meta;

    [Managed]
    public class ConvidadoBase implements IExternalizable, IUID {

        protected var _em:IEntityManager = null;

        private var __initialized:Boolean = true;
        private var __detachedState:String = null;

        private var _codigo:Number;
        private var _email:String;
        private var _id:String;
        private var _nome:String;
        private var _observacao:String;
        private var _status:String;
        private var _telefone:String;
        private var _version:Number;

        meta function isInitialized(name:String = null):Boolean {
            if (!name)
                return __initialized;

            var property:* = this[name];
            return (
                (!(property is Convidado) || (property as Convidado).meta::isInitialized()) &&
                (!(property is IPersistentCollection) || (property as IPersistentCollection).isInitialized())
            );
        }

        [Transient]
        public function meta_getEntityManager():IEntityManager {
            return _em;
        }
        public function meta_setEntityManager(em:IEntityManager):void {
        	_em = em;
        }
    
    	public static const meta_constraints:Array = [
    		{ property: "nome",
				blank: "false"
    		}, 
    		{ property: "status",
				inList: "[Bloqueado, Autorizado]"
    		}, 
    		{ property: "observacao",
				blank: "true", widget: "textArea"
    		}, 
    		{ property: "codigo" }, 
    		{ property: "email" }, 
    		{ property: "telefone" }
		]

        public function set codigo(value:Number):void {
            _codigo = value;
        }
        public function get codigo():Number {
            return _codigo;
        }

        public function set email(value:String):void {
            _email = value;
        }
        public function get email():String {
            return _email;
        }

        public function set id(value:String):void {
            _id = value;
        }
        [Id]
        public function get id():String {
            return _id;
        }

        public function set nome(value:String):void {
            _nome = value;
        }
        public function get nome():String {
            return _nome;
        }

        public function set observacao(value:String):void {
            _observacao = value;
        }
        public function get observacao():String {
            return _observacao;
        }

        public function set status(value:String):void {
            _status = value;
        }
        public function get status():String {
            return _status;
        }

        public function set telefone(value:String):void {
            _telefone = value;
        }
        public function get telefone():String {
            return _telefone;
        }

        public function set version(value:Number):void {
            _version = value;
        }
        [Version]
        public function get version():Number {
            return _version;
        }
/*
        public function set uid(value:String):void {
            // noop... XOVAA
        }
        public function get uid():String {
            if (!_id)
                return UIDUtil.createUID();
            return getQualifiedClassName(this) + "#[" + String(_id) + "]";
        }
*/


        public function meta_merge(em:IEntityManager, obj:*):void {
            var src:ConvidadoBase = ConvidadoBase(obj);
            __initialized = src.__initialized;
            __detachedState = src.__detachedState;
            if (meta::isInitialized()) {
               	em.meta_mergeExternal(src._codigo, _codigo, null, this, 'codigo', function setter(o:*):void{_codigo = o as Number});
               	em.meta_mergeExternal(src._email, _email, null, this, 'email', function setter(o:*):void{_email = o as String});
               	em.meta_mergeExternal(src._id, _id, null, this, 'id', function setter(o:*):void{_id = o as String});
               	em.meta_mergeExternal(src._nome, _nome, null, this, 'nome', function setter(o:*):void{_nome = o as String});
               	em.meta_mergeExternal(src._observacao, _observacao, null, this, 'observacao', function setter(o:*):void{_observacao = o as String});
               	em.meta_mergeExternal(src._status, _status, null, this, 'status', function setter(o:*):void{_status = o as String});
               	em.meta_mergeExternal(src._telefone, _telefone, null, this, 'telefone', function setter(o:*):void{_telefone = o as String});
               	em.meta_mergeExternal(src._version, _version, null, this, 'version', function setter(o:*):void{_version = o as Number});
            }
            else {
               em.meta_mergeExternal(src._id, _id, null, this, 'id', function setter(o:*):void{_id = o as String});
            }
        }

        public function readExternal(input:IDataInput):void {
            __initialized = input.readObject() as Boolean;
            __detachedState = input.readObject() as String;
            if (meta::isInitialized()) {
                _codigo = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
                _email = input.readObject() as String;
                _id = input.readObject() as String;
                _nome = input.readObject() as String;
                _observacao = input.readObject() as String;
                _status = input.readObject() as String;
                _telefone = input.readObject() as String;
                _version = function(o:*):Number { return (o is Number ? o as Number : Number.NaN) } (input.readObject());
            }
            else {
                _id = input.readObject() as String;
            }
        }

        public function writeExternal(output:IDataOutput):void {
            output.writeObject(__initialized);
            output.writeObject(__detachedState);
            if (meta::isInitialized()) { 
                output.writeObject((_codigo is IPropertyHolder) ? IPropertyHolder(_codigo).object : _codigo); 
                output.writeObject((_email is IPropertyHolder) ? IPropertyHolder(_email).object : _email); 
                output.writeObject((_id is IPropertyHolder) ? IPropertyHolder(_id).object : _id); 
                output.writeObject((_nome is IPropertyHolder) ? IPropertyHolder(_nome).object : _nome); 
                output.writeObject((_observacao is IPropertyHolder) ? IPropertyHolder(_observacao).object : _observacao); 
                output.writeObject((_status is IPropertyHolder) ? IPropertyHolder(_status).object : _status); 
                output.writeObject((_telefone is IPropertyHolder) ? IPropertyHolder(_telefone).object : _telefone); 
                output.writeObject((_version is IPropertyHolder) ? IPropertyHolder(_version).object : _version);
            }
            else {
                output.writeObject(_id);
            }
        }
    }
}
